version: '3.8'

services:
  go-app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  node-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
